import { type NextPage } from "next";
import Head from "next/head";

import Navbar from "@/components/NavBar";
import QuickActions from "@/components/QuickActions/QuickActions";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import AccountInput from "@/components/AccountInput";

import { motion } from "framer-motion";
import { ArrowLeftIcon, CrossIcon, SidebarCloseIcon } from "lucide-react";

type View = "Accounts" | "Review" | "Overview";

const ViewsButtons = ({
  onChange,
  value,
}: {
  onChange: (value: View) => void;
  value: View;
}) => {
  return (
    <div className="flex gap-2 py-4">
      {value !== "Overview" ? (
        <>
          <motion.div layoutId={"1"} layout>
            <Button
              onClick={() => onChange("Overview")}
              className="0 rounded-full bg-gray-800 text-xl dark:bg-gray-900   dark:text-white"
            >
              <ArrowLeftIcon />
            </Button>
          </motion.div>
          <motion.div layoutId={"2"} layout>
            <Button className="rounded-full bg-gray-100 text-gray-900 hover:bg-gray-100 ">
              {value}
            </Button>
          </motion.div>
        </>
      ) : (
        <>
          <motion.div layout layoutId={"1"}>
            <Button
              onClick={() => onChange("Accounts")}
              className="rounded-full bg-gray-800 dark:bg-gray-900 dark:text-white"
            >
              Accounts
            </Button>
          </motion.div>
          <motion.div layout layoutId="2">
            <Button
              onClick={() => onChange("Review")}
              className="rounded-full bg-gray-800 dark:bg-gray-900 dark:text-white"
            >
              Review
            </Button>
          </motion.div>
        </>
      )}
    </div>
  );
};

const Home: NextPage = () => {
  const [view, setView] = useState<View>("Overview");

  return (
    <div className="dark">
      <Head>
        <title>Alcent</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-[100%] flex-col items-center justify-around px-4 py-6">
        <div className="w-[100%] max-w-[1000px]">
          <Navbar />

          <ViewsButtons onChange={setView} value={view} />
          {view === "Overview" ? (
            <QuickActions />
          ) : view === "Accounts" ? (
            <div>accounts</div>
          ) : (
            <div>review</div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Home;
